### ISSUE TITLE
Switch to using time ranges

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#105]
Currently we provide start and end time separately. An alternative might be to supply a time range instead. This is supported by
[ISO8601](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals). Following Javier's suggestion in ESMValTool, this might look something like this:

```
# Years
timespan: 1980/2020

# More granular options
timespan: 198012/202011

# Full spec
timespan: 2007-03-01T13:00:00Z/2008-05-11T15:30:00Z

# Start and duration
timespan: 1980/P3Y
timespan: 198005/P3M
```

**Comment by sverhoeven** [comment]
Is there a Python package that can parse those strings into 2 datetime objects? dateutil does not seem to support it.

**Comment by Peter9192** [comment]
I'll look into that. I noticed I forgot to point to Javier's original proposal. Might be nice to monitor how they're doing it there: https://github.com/ESMValGroup/ESMValCore/issues/1120#issuecomment-851419735

**Comment by SarahAlidoost** [comment]
I couldn't understand the advantages of the format `timespan: 2007-03-01T13:00:00Z/2008-05-11T15:30:00Z` in eWaterCycle API specifically. What will be improved here?

**Comment by Peter9192** [comment]
> 
> 
> Is there a Python package that can parse those strings into 2 datetime objects? dateutil does not seem to support it.

There you go: https://pyiso8601.readthedocs.io/en/latest/#

**Comment by sverhoeven** [comment]
Tested pyiso8601
```python
import iso8601

iso8601.parse_date('2007-03-01T13:00:00Z/2008-05-11T15:30:00Z')
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
<ipython-input-2-f9de30bccfec> in <module>
----> 1 iso8601.parse_date('2007-03-01T13:00:00Z/2008-05-11T15:30:00Z')

~/miniconda39/envs/ewatercycle/lib/python3.9/site-packages/iso8601/iso8601.py in parse_date(datestring, default_timezone)
    193     m = ISO8601_REGEX.match(datestring)
    194     if not m:
--> 195         raise ParseError("Unable to parse date string %r" % datestring)
    196     groups = m.groupdict()
    197 

ParseError: Unable to parse date string '2007-03-01T13:00:00Z/2008-05-11T15:30:00Z'
```
Does not seem to understand ranges.

**Comment by Peter9192** [comment]
OK let's close this as not urgent enough
