### ISSUE TITLE
Remove default options for filenames and more?

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#110]
Following the discussion in https://github.com/eWaterCycle/ewatercycle/pull/98#discussion_r645446917, we would like to remove the default options for some model-specific options in the forcing module. 

Examples of options we might remove:

- `_marrmot.py`: `forcing_file: Optional[str]  = 'marrmot.nc`  --> model names usually more specific
- `_wflow.py`: `netcdfinput: Optional[str] = "inmaps.nc"` --> model names usually more specific

Examples of options might want to keep:

- `_wflow.py`: `Precipitation: Optional[str] = "/pr"` --> nudge towards using cmor names, may save some typing as well.
- `_marrmot.py`: `shape: Optional[str] = None`  --> not model specific, but comes before `**forcing_info` e.g. when called from `load_foreign`, which is an issue that needs to be solved.

**Comment by BSchilperoort** [comment]
Kind of stale with the models being moved to their own plugins in V2. Could be good for the model owners to tackle in their plugins, but not relevant here anymore.
