### ISSUE TITLE
Remove path from model.parameters

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#113]
We dont want path in `model.parameters` like forcing directory. It should be fixed in [lisflood](https://github.com/eWaterCycle/ewatercycle/blob/955499d89f30a0d4a45dd26037ee9caae1a6206d/ewatercycle/models/lisflood.py#L245), [marrmotm01](https://github.com/eWaterCycle/ewatercycle/blob/955499d89f30a0d4a45dd26037ee9caae1a6206d/ewatercycle/models/marrmot.py#L251), and [marrmotm14](https://github.com/eWaterCycle/ewatercycle/blob/955499d89f30a0d4a45dd26037ee9caae1a6206d/ewatercycle/models/marrmot.py#L504).

**Comment by sverhoeven** [comment]
One exception:
If the path can be given to the `model.setup()` method, then it should show up in `model.parameters`. See #121
