### ISSUE TITLE
Move docker images to central registry

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#119]
Currently each `ewatercycle.model.*` has a `_get_docker_image` and `_get_singularity_image`. The images are coupled to the `available_versions` class property. 

Ideally the system administrator would pull/build all images so the user can just start them. If they are not available, this leads to issues (https://github.com/eWaterCycle/grpc4bmi/issues/100 and https://github.com/eWaterCycle/grpc4bmi/issues/95). 

It would be nice to have a new module for administrators to build/pull all images. This would hold a registry of all the docker containers and the names of the corresponding singularity images. The `ewatercycle.models.*` classes could then get the docker/singularity images from this module, instead of having it hardcoded.

**Comment by sverhoeven** [comment]
Now using `ewatercycle.CFG['singularity_dir']` dir for sif files see https://ewatercycle.readthedocs.io/en/latest/system_setup.html#id2
