### ISSUE TITLE
Setup guide for system admins

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#120]
Things a system admin should do before users can start using the ewaterycycle package should be documented.

1. Create conda env with ewatercycle package
2. install Docker / singularity
3. Pull /build container images #119
4. Download example parameter sets
5. Download example forcing for Marrmot
5. Prepare other parameter sets
4. Setup ESMValTool
5. Download OBS ERA5 with era5cli
3. Create /etc/ewatrercycle.yaml

**Comment by Peter9192** [comment]
Nice list! I guess this all goes into a "Deployment" section in the documentation (as opposed to the "User manual" section).

**Comment by sverhoeven** [comment]
Could consume https://github.com/eWaterCycle/ewatercycle/blob/master/docs/hpc_to_cluster.rst
