### ISSUE TITLE
Add schema for ewatercycle.yaml

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#122]
Instead of using a copy of the matplotlib validitors use a yaml validator from PyPI like https://pypi.org/project/yamale/

**Comment by Peter9192** [comment]
Perhaps we could also look at [confuse](https://confuse.readthedocs.io/en/latest/usage.html)

**Comment by BSchilperoort** [comment]
We use Pydantic for validation nowadays.
