### ISSUE TITLE
Lisflood: Refactor _create_lisflood_config to accept other formats than .nc for MaskMap

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#123]
Currently, in lisflood module, in [_create_lisflood_config](https://github.com/eWaterCycle/ewatercycle/blob/dfca1cbed2b741ef2e720e589c6efb21137b8d86/ewatercycle/models/lisflood.py#L161), it is assumed that `MaskMap` has `.nc` format. But `MAskMap` can have other formats like `.map`. This [line](https://github.com/eWaterCycle/ewatercycle/blob/dfca1cbed2b741ef2e720e589c6efb21137b8d86/ewatercycle/models/lisflood.py#L182) needs a refactoring.

**Comment by sverhoeven** [comment]
Yep, if we want to use https://github.com/ec-jrc/lisflood-usecases as example parameter set we need support for [mask.map](https://github.com/ec-jrc/lisflood-usecases/blob/master/LF_lat_lon_UseCase/maps/mask.map) , see eWaterCycle/ewatercycle-lisflood#12

**Comment by SarahAlidoost** [comment]
As mentioned in eWaterCycle/ewatercycle-lisflood#12, we cannot use other use-cases for now. However, I think the lisflood class can be refactored to avoid` .rstrip('.nc')`.
