### ISSUE TITLE
Remove unused keys from ewatercycle config validators

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#130]
Currently, the [config validators](https://github.com/eWaterCycle/ewatercycle/blob/3ba5df440d44f3d7eaeaa7de66a3b09f9c492454/ewatercycle/config/_validators.py#L131) contains unused model specific settings keys like `wflow.singularity_image`. Those keys should be removed.

**Comment by Peter9192** [comment]
This is fixed in #118

**Comment by sverhoeven** [comment]
And `esmvaltool_config` has own issue #152
