### ISSUE TITLE
Wflow example notebook requires editing generated config file

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#132]
In https://github.com/eWaterCycle/ewatercycle/blob/master/docs/examples/wflow.ipynb there is a `Update the config file` chapter which asks the user to modify the config file generated by `model.setup()` before calling `model.initialize()`. While running the notebook I did not expect to have to do manual edits. I also expect users of the package will be surprised. 

Can the model class add the `[API]` section itself when missing?

As it knows which container image (version of model code) will be run and what a compatible configuration file should look like.

**Comment by Peter9192** [comment]
That might be a good idea.
