### ISSUE TITLE
Add cfg_dir argument to setup of Pcrglobwb, wlfow 

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#133]
Pcrglobwb, wlfow do not have cfg_dir or work_dir as argument for setup(). So cfg_dir will need to be added to be similar to PyMT interface and other models.

**Comment by SarahAlidoost** [comment]
steup should get and return `cfg_dir` as a string.

**Comment by sverhoeven** [comment]
Fixed in #142
