### ISSUE TITLE
Add directory argument to forcing.generate()

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#145]
The forcing generate method now always generates a sub directory inside ESMValtools `output_dir`. It would be nice if the directory could be given.

Like shown in docs/examples/ewatercycle_api_notebook.ipynb as 
```
 #location on the file system where the output will but placed. Optional, otherwise generated.
    directory='/path/to/forcing/output/',
```

**Comment by BSchilperoort** [comment]
Fixed years ago
