### ISSUE TITLE
API docs missing for most models

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#154]
Only https://ewatercycle.readthedocs.io/en/latest/apidocs/ewatercycle.models.lisflood.html shows the docstrings of the class/constructor and setup method. The [marrmot](https://ewatercycle.readthedocs.io/en/latest/apidocs/ewatercycle.models.marrmot.html), pcrglobwb and wflow sub modules are empty.

To use the model it would be nice to know how to construct it and set it up as part of the API documentation.

**Comment by Peter9192** [comment]
Looks like a RTD thing. The [latest build](https://readthedocs.org/projects/ewatercycle/builds/14196178/) prints the following warnings in the output (but passes nonetheless):


```
WARNING: autodoc: failed to import module 'models' from module 'ewatercycle'; the following exception was raised:
No module named 'grpc'
WARNING: autodoc: failed to import module 'models.marrmot' from module 'ewatercycle'; the following exception was raised:
No module named 'grpc'
WARNING: autodoc: failed to import module 'models.pcrglobwb' from module 'ewatercycle'; the following exception was raised:
No module named 'grpc'
WARNING: autodoc: failed to import module 'models.wflow' from module 'ewatercycle'; the following exception was raised:
No module named 'grpc'
/home/docs/checkouts/readthedocs.org/user_builds/ewatercycle/checkouts/140/docs/examples/ewatercycle_api_notebook.ipynb:328: WARNING: Title level inconsistent:
```
