### ISSUE TITLE
Reduce code duplication of _coords_to_indices

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#157]
Seems _coords_to_indices in all gridded models are almost the same. Can we move the duplicated code to util.py?

**Comment by Peter9192** [comment]
So far the differences are in three lines (bmi fetching), but since the original shape that comes from bmi is still relevant later on, I'd like to keep those functions close together for now - and that means at this stage they're still model-specific.

**Comment by BSchilperoort** [comment]
Not relevant anymore with ewatercycle 2.0 (only one implementation in base.model, plugins can override if necessary)
