### ISSUE TITLE
Example parameters sets should have model and catchment in name

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#166]
The  https://github.com/eWaterCycle/ewatercycle/blob/33d74cb7bed8def40ef7d1cda79f79e4dcdc75cf/ewatercycle/parameter_sets/__init__.py#L84 method returns following keys `['wflow_rhine_sbm_nc', 'pcrglobwb_example_case', 'lisflood_fraser']`. From the pcrglobwb name I can not tell which catchment it is for. Can Rhine be added to its name?

**Comment by Peter9192** [comment]
> Can Rhine be added to its name?

Sure, I think this was very arbitrary when we first chose it.

**Comment by Peter9192** [comment]
Addressed in #170
