### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#168]
Currently some notebooks are pulling the ewatercycle logo from the (external) ewatercycle website. It would be better to add it to the repo and ship it with the package. I do this in https://github.com/eWaterCycle/ewatercycle/pull/167. Perhaps cherry-pick the first commit to that branch in other notebook PRs?

**Comment by SarahAlidoost** [comment]
It is better if we don't use a relative path for logo like `./logo.png`. Because if users copy only the notebook, the logo will break.

**Comment by sverhoeven** [comment]
@SarahAlidoost you prefer to use 

```markdown
![logo](https://www.ewatercycle.org/assets/logo.png)
```
?

I agree that URL is stable and we don't need to care about relativeness or inclusion during build.

**Comment by SarahAlidoost** [comment]
> @SarahAlidoost you prefer to use
> 
> ```gfm
> ![logo](https://www.ewatercycle.org/assets/logo.png)
> ```
> 
> ?
> 
> I agree that URL is stable and we don't need to care about relativeness or inclusion during build.

In the notebook, I prefer to use `![logo](https://github.com/eWaterCycle/ewatercycle/raw/main/docs/examples/logo.png)` instead of `![logo](./logo.png)`.

**Comment by Peter9192** [comment]
Shouldn't it be https://raw.githubusercontent.com/eWaterCycle/ewatercycle/main/docs/examples/logo.png ?

**Comment by sverhoeven** [comment]
https://github.com/eWaterCycle/ewatercycle/raw/main/docs/examples/logo.png redirects to https://raw.githubusercontent.com/eWaterCycle/ewatercycle/main/docs/examples/logo.png
Better to use URL that GH advertises on its page, instead of where it ends.
