### ISSUE TITLE
Readthedocs failed to build 'latest'

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#177]
**Note:** disabled PDF and EPUB build in RTD as a temporary fix. Ideally these should be re-enabled.

It seems the last successful build of main was on 9 juli. We [switched to 'main'](https://github.com/eWaterCycle/ewatercycle/issues/139#issuecomment-878109420) on 12 juli around 11:10. After that, no new builds for 'latest' were attempted until I manually tried it today. When I tried it manually today, it failed with

```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/ewatercycle/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 2151, in depart_codearea_latex
    assert 'Verbatim' in lines[0]
AssertionError
```

even though PR builds in the meantime have passed.

**Comment by Peter9192** [comment]
I changed the latest tag on RTD to point to `main` and resynced the webhook. Still need to confirm that this fixes the automatic build trigger when something is merged to main. **Update**: trigger works again.

**Comment by Peter9192** [comment]
I noticed that there's a difference between building a PR and building latest. The former [only builds the HTML page](https://docs.readthedocs.io/en/stable/pull-requests.html#limitations), whereas the latter also builds a PDF and EPUB. I tried swithing off EPUB and PDF in RTD config, and now the build passes. 

Apart from renaming to main, there were three PRs that could have broken the PDF build in the meantime: #158, #163, and #169. If we can identify the breaking change, we can re-enable the PDF and EPUB build.

**Comment by Peter9192** [comment]
Error is triggered here: 
https://github.com/spatialaudio/nbsphinx/blob/810580b8c5235333ccf1d41296080136ee02e185/src/nbsphinx.py#L2153

**Comment by SarahAlidoost** [comment]
After removing `~/.config/ewatercycle/ewatercycle.yaml `, I run `cd docs` and `make html`. it returns this error:
```
Notebook error:
PandocMissing in examples/Irrigation.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
make: *** [Makefile:20: html] Error 2
```

**Comment by sverhoeven** [comment]
Seems nbsphinx needs pandoc see https://nbsphinx.readthedocs.io/en/0.8.6/installation.html#pandoc which is already installed on readthedocs.org, but may not be locally.

**Comment by Peter9192** [comment]
Maybe we should add pandoc to environment.yml and/or add to contribute.md

**Comment by Peter9192** [comment]
Closing as we agree that PDF is not really necessary
