### ISSUE TITLE
Jupyter lab returns model log info 

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#184]
When running notebooks on cartesius, the model log messages appear in the output cells. This happens for marrmot, wflow and lisflood on cartesius that uses singularity. Here is an example using marrmot: 
**On Cartesius with singularity:**
```python

from grpc4bmi.bmi_client_singularity import BmiClientSingularity
model = BmiClientSingularity(image="ewatercycle-marrmot-grpc4bmi_2020.11.sif", work_dir=".")
```
```pycon
error: graphics_toolkit: gnuplot version too old.
error: called from
    graphics_toolkit at line 88 column 9
warning: function /opt/MARRMoT/Octave/fzero.m shadows a core library function
error: graphics_toolkit: gnuplot version too old.
error: called from
    graphics_toolkit at line 88 column 9
model =

<object marrmotBMI_oct>
```
```python
!singularity version
```
```pycon
3.8.0-1.el7_9
```
```python
!conda list jupyter
```
```pycon
# packages in environment at /home/fakhereh/miniconda3/envs/ewatercycle:
#
# Name                    Version                   Build  Channel
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyter-server            1.9.0                    pypi_0    pypi
jupyterlab                3.0.16                   pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-server         2.6.0                    pypi_0    pypi
```

**locally with Docker:**
```python

from grpc4bmi.bmi_client_docker import BmiClientDocker
model = BmiClientDocker(image="ewatercycle/marrmot-grpc4bmi:2020.11", image_port=55555, work_dir=".")
```
```pycon
```
```python
!conda list jupyter
```
```pycon
# packages in environment at /home/sarah/anaconda3/envs/ewatercycle:
#
# Name                    Version                   Build  Channel
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyter-server            1.9.0                    pypi_0    pypi
jupyterlab                3.0.16                   pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-server         2.6.1                    pypi_0    pypi
```

**Comment by SarahAlidoost** [comment]
The jupyter versions are the same on cartesius and on my laptop. The example shows that the log messages don't appear when using docker. Another test would be to run singularity locally. I found the singularity installation's latest version painful :disappointed:

**Comment by sverhoeven** [comment]
In grpc4bmi the Docker container is started detached, thats why no output appears in notebook or jupyter log. 
In grpc4bmi the singularity container is started with popen and its stdout/stderr handlers are inherited from the Python process running the notebook.  

In [ipykernel v6.0.0](https://github.com/ipython/ipykernel/releases/tag/6.0.0) a feature was added to forward all stdout/stderr from popen to notebook.

So any version of singularity will cause logging in notebook. 

I can add stdout/stderr arguments to BmiClientSingularity so its possible to redirect the output to devnull.

**Comment by sverhoeven** [comment]
Created https://github.com/eWaterCycle/grpc4bmi/pull/102 to redirect logs. Could you try it out?

First install grpc4bmi from `sing-capture-output` branch locally then in notebook run:
```python
import subprocess
from grpc4bmi.bmi_client_singularity import BmiClientSingularity
model = BmiClientSingularity(image="ewatercycle-marrmot-grpc4bmi_2020.11.sif", 
                             work_dir=".",
                             stderr=subprocess.DEVNULL, # Or open('mylog.txt','w')
                             stdout=subprocess.DEVNULL,
                             )
```

**Comment by sverhoeven** [comment]
If https://github.com/eWaterCycle/grpc4bmi/pull/102 works I can create a new release for grpc4bmi. 

In ewatercycle package how should set these new args?
1. Set to `subprocess.DEVNULL`, so user is unable to get logs
2. Set to a file object 
  1.Log file name as argument of setup() or constructor
  2. A Temporary file or memory file (StringIO) is used and model.logs() can retrieve contents
3. Or mimic Docker and add `logs()` method to BmiClientSingularity class, which uses temporary file internally
4. Redirect stdout/stderr of container to logging library
5. Something else

**Comment by sverhoeven** [comment]
Go for option 4, also add logs() method to Docker. BmiClientSingularity(stdout=None) means writes to SpooledTemporaryFile

**Comment by sverhoeven** [comment]
[grpc4bmi v0.2.13](https://pypi.org/project/grpc4bmi/0.2.13/) has been released with fix. 

Please update with `pip install grpc4bmi==0.2.13`

**Comment by Peter9192** [comment]
Thanks @sverhoeven !
