### ISSUE TITLE
Add plot method to forcing classes

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#189]
We already have nice example plots of the forcing for most models (https://ewatercycle.readthedocs.io/en/latest/examples/generate_forcing.html). It would be nice to move those to the model-specific forcing classes, so one could just call `forcing.plot()`

**Comment by BSchilperoort** [comment]
Easy access to the xarray DataArrays and therefore plotting is added in #393.

Model-specific forcing classes will have to implement this in their own plugin.
