### ISSUE TITLE
Add column name argument to ewatercycle.observation.grdc.get_grdc_data

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#190]
Now the pandas dataframe returned by `ewatercycle.observation.grdc.get_grdc_data()` always has `streamflow` as a column. Using it in `ewatercycle.analysis.hydrograph()` always needs renaming it to `reference` or `observation` with
```python
observations_df = observations_df.rename(columns={'streamflow': 'observation'})
```

Can the default column name be changed or an argument be added to set the column name?

**Comment by SarahAlidoost** [comment]
nice idea. I think that the second option (an argument to set the name) is better. I like keeping the variable name `streamflow` as the default column name.
