### ISSUE TITLE
Missing pandoc in building documentation locally

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#196]
After removing `~/.config/ewatercycle/ewatercycle.yaml `, I run `cd docs` and `make html`. it returns this error:
```
Notebook error:
PandocMissing in examples/Irrigation.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
make: *** [Makefile:20: html] Error 2
```

_Originally posted by @SarahAlidoost in https://github.com/eWaterCycle/ewatercycle/issues/177#issuecomment-883264906_

**Comment by Peter9192** [comment]
Maybe we should add pandoc to environment.yml and/or add to contribute.md?

**Comment by sverhoeven** [comment]
The environment.yml is for end-users, they will not need to build docs. So I would add it to Contributing guidelines
