### ISSUE TITLE
Making release description hard due to RestructuredText to Markdown conversion

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#199]
The [making a release instructions](https://github.com/eWaterCycle/ewatercycle/blob/main/CONTRIBUTING.rst) ask for copying text from the README.rst and CHANGELOG.rst to the GH release description form field. However the GH release form requires Markdown and the files are in RestructuredText.

For now we used pandoc to convert with
```shell
pandoc -s README.rst -o README.md
pandoc -s CHANGELOG.rst -o CHANGELOG.md
```

It would be nice if the conversion would not be needed or at least was documented.

**Comment by Peter9192** [comment]
I guess we can simply use .md in the repo as well, no?
