### ISSUE TITLE
Error when input path in ewatercycle.parameter_sets.ParameterSet isnot subpath of CFG["parameterset_dir"]

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#201]
On Jupyter machine, we have `CFG['parameterset_dir']: PosixPath('/mnt/data/parameter-sets')`. When I run:
```python
parameterset = ewatercycle.parameter_sets.ParameterSet(
    name="merrimack_parameterset",
    directory="/mnt/data/examples/technical_paper/pcr-globwb/input",
    config="/mnt/data/examples/technical_paper/pcr-globwb/input/merrimack_05min_era5.ini",
    target_model="pcrglobwb",
    doi="10.5281/zenodo.1045339",
    supported_model_versions={"setters"},
)
```
It returns an error:
```python
ValueError: Input path /mnt/data/examples/technical_paper/pcr-globwb/input is not a subpath of parent /mnt/data/parameter-sets
```
The reason is that, in `init` function of [ewatercycle/parameter_sets/default.py](https://github.com/eWaterCycle/ewatercycle/blob/5135c038ec7a1997aeb8cbf1ab0762d2f329984d/ewatercycle/parameter_sets/default.py#L33), we set `CFG['parameterset_dir'] `as parent.

I think to fix the issue, user should change `CFG["parameterset_dir"]` before calling `ewatercycle.parameter_sets.ParameterSet`. So, this should be added to the notebooks like [Case2 notebook](https://github.com/eWaterCycle/technicalPaperExampleNotebooks/blob/0e5e8c1ca3126564c497cf59d60a21ee9880b3af/Case2ForcePCRGlobWBWithadditionalEvapInfo.ipynb).

**Comment by sverhoeven** [comment]
Fixes in main branch. Now PararmeterSet directory does not have to be inside CFG['parameterset_dir'].
