### ISSUE TITLE
Update docs on modification of USGS

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#209]
We have documentation here: https://ewatercycle.readthedocs.io/en/latest/observations.html
Need to add info about modifications made in https://github.com/eWaterCycle/ewatercycle/blob/main/ewatercycle/observation/usgs.py.

@jeromaerts can you make a PR for this?

**Comment by jeromaerts** [comment]
@Peter9192 I will work on this PR this week.

**Comment by jeromaerts** [comment]
@Peter9192, I had a look at the pyoos data collector used in this script. The code in line: https://github.com/ioos/pyoos/blob/908660385029ecd8eccda8ab3a6b20b47b915c77/pyoos/parsers/waterml.py#L72 states that the data is corrected to the UTC timezone. 

We download the UTC data in cubic feet per second and convert this to cubic meter per second: https://github.com/eWaterCycle/ewatercycle/blob/a4fc868bf320702414cc9b71e87a86ea05719665/ewatercycle/observation/usgs.py#L88-L90  (this line could use a comment stating more clearly that we convert the units by dividing them by a set value. 

I will make a PR for the docs clearly stating that the timestamp is corrected to UTC and that the Units are converted.

**Comment by sverhoeven** [comment]
@jeromaerts made https://github.com/eWaterCycle/ewatercycle/pull/215 which fixed this issue
