### ISSUE TITLE
Include example notebooks in default user homes on eWaterCycle infra

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#212]
so they can quickly get started

Use https://github.com/jupyterhub/nbgitpuller

**Comment by sverhoeven** [comment]
nbgitpuller is installed in VM at https://github.com/eWaterCycle/infra/blob/ee4a8b30eddce0732a43d1ff036ecb1dfbafecfc/roles/ewatercycle/files/environment.yml#L72
and Terria explorer has links which will clone the ewatercycle repo to home dir and opens [docs/examples/MarrmotM01.ipynb](https://github.com/eWaterCycle/ewatercycle/blob/main/docs/examples/MarrmotM01.ipynb), see https://github.com/eWaterCycle/TerriaMap/blob/56f67fbd5b37f683cbfc31861c03cb9793aadd8f/lib/Views/UserInterface.jsx#L33
