### ISSUE TITLE
Pin esmf version

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#234]
For running notebooks using parallel processing (for example case3 of technical paper), the version of esmf should be set in the environment file as:
```yml
 - esmpy!=8.1.0
```
See [this](https://github.com/ESMValGroup/ESMValCore/issues/1208) for details. 
I submitted a job to run the case3 notebook. @sverhoeven and @Peter9192 shall we add this issue to v1.1.0 milestone or wait for the notebook result?

**Comment by Peter9192** [comment]
Good that you found a fix (hopefully). Let's add it to the milestone then!
