### ISSUE TITLE
Drop requirements.txt in favor of .[dev]

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#24]
The https://github.com/eWaterCycle/ewatercycle/blob/master/requirements.txt and https://github.com/eWaterCycle/ewatercycle/blob/8473707e441a9361380fec8a5f9b879fc3cda9a1/setup.py#L59 are both describing developement dependencies. It would be nice if there was just one place for the dev dependencies.

Can the content of requirements.txt be moved to dev extras in setup.py?

Please also document in README or CONTRIBUTING.rst how they should be installed:
```
pip install -e .[dev]
```

**Comment by Peter9192** [comment]
I noticed RTD uses the requirements.txt. Can we make it use setup.py instead? Also see #31
