### ISSUE TITLE
Remove caching mechanism from get_usgs_data()

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#240]
To use [ewatercycle.observation.usgs.get_usgs_data](https://ewatercycle.readthedocs.io/en/latest/apidocs/ewatercycle.observation.usgs.html) you need to specify a `cache_dir` or have a USGS_DATA_HOME env var set. It would be nice if that flag was not needed.

**Comment by Peter9192** [comment]
Is there a reason it is cached (as opposed to stored persistently)?

**Comment by sverhoeven** [comment]
To download USGS observations you need to talk to a web service. To not talk to the web service each time for the same request a caching mechanism was implemented. If USGS discharge data where available as files we could have had a mirror, but I could not find them on [their website](https://waterservices.usgs.gov/).

**Comment by sverhoeven** [comment]
We could also just remove the caching mechanism, this will make the code easier. No caching could give users [a forbidden error](https://waterservices.usgs.gov/docs/faq.html) when they (or the ip address that they are behind) are using it heavily, but I think we should fix that when it arises and not before.

**Comment by Peter9192** [comment]
I agree, let's not make it needlessly complex.
