### ISSUE TITLE
Copy shapefile to forcing dir if not already present

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#247]
got log message: 

`Shapefile /mnt/home/user37/technicalPaperExampleNotebooks/settingFiles/Merrimack.shp is not in forcing directory /mnt/home/user37/technicalPaperExampleNotebooks/esmvaltool_output/recipe_marrmot_20210826_141923/work/diagnostic_daily/script. So, it won't be saved in /mnt/home/user37/technicalPaperExampleNotebooks/esmvaltool_output/recipe_marrmot_20210826_141923/work/diagnostic_daily/script/ewatercycle_forcing.yaml.`

It would be nice if we could just copy the file to that directory.

**Comment by BSchilperoort** [comment]
Shapefiles are copied since #393
