### ISSUE TITLE
get_usgs_data() should return same type as get_grdc_data()

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#253]
I noticed that `get_grdc_data()` returns a pandas dataframe and metadata dict while `get_usgs_data()` returns an xarray. The grdc change was done in https://github.com/eWaterCycle/ewatercycle/issues/109 . Should we not make both observation fetchers have similar API.

A `column` argument should be added to make both methods more similar.

**Comment by Peter9192** [comment]
I agree that would be more intuitive
