### ISSUE TITLE
Run of user guide notebook fails at wflow intialize

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#277]
I try to run the user guide notebook on snellius, see the notebook in [this PR](https://github.com/eWaterCycle/ewatercycle/pull/276). The cell running `model_instance.initialize(cfg_file) ` took a long time to complete, ` wflow version="2020.1.1"`. The log file can be found here `/scratch-shared/ewatercycle/wflow_20211129_105649/run_default/wflow.log`. There, an error is reported as: `wf_netcdfio - ERROR - EPGS not converted correctly: EPSG:4326. Is the GDAL_DATA environment variable set correctly?`

**Comment by SarahAlidoost** [comment]
see this [comment](https://github.com/eWaterCycle/ewatercycle/pull/268#issuecomment-938468873) by @sverhoeven .

**Comment by sverhoeven** [comment]
As a workaround we could use wflow version="2020.1.2", but it would be nice to fix wflow version="2020.1.1" image as well.

**Comment by Peter9192** [comment]
So can this be fixed by explicitly setting the GDAL_DATA env variable somewhere?

**Comment by sverhoeven** [comment]
Yes it can, by setting in the Dockerfile like was done for the 2020.1.2 Docker image at https://github.com/eWaterCycle/grpc4bmi-examples/blob/d9291c11de3859248f3926aa5e2aa0f987c9afdf/wflow/Dockerfile#L13

**Comment by jeromaerts** [comment]
I have the exact same problem with the wflow 2020.1.3 container while using singularity. @sverhoeven was your fix implemented when building the 2020.1.3 image?
