### ISSUE TITLE
PCRGLOB setup timeout

### ISSUE THREAD

**Issue by jeromaerts** [eWaterCycle/ewatercycle#287]
When I run the example parameter set of PCRGLOBWB as described here: https://ewatercycle.readthedocs.io/en/latest/examples/pcrglobwb.html, I receive a timeout after 300 sec. when running the .setup function.

I try to run the example using the singularity container found here on Snellius: "/gpfs/work1/0/wtrcycle/singularity-images/ewatercycle-pcrg-grpc4bmi_setters.sif"

**Comment by Peter9192** [comment]
Note: when I first reproduced the problem I was accidentily running on the login node. This only works on a compute node.

I was able to run the PCRGLob example case, but I had to change the path of the forcing directory here:

```Python
forcing = ewatercycle.forcing.load_foreign(
    target_model="pcrglobwb",
    start_time="2001-01-01T00:00:00Z",
    end_time="2010-12-31T00:00:00Z",
    directory="/projects/0/wtrcycle/parameter-sets/pcrglobwb_rhinemeuse_30min/forcing",
    shape=None,  # if available, it can be used e.g. for plotting
    forcing_info=dict(
        # model-specific options
        precipitationNC="precipitation_2001to2010.nc",
        temperatureNC="temperature_2001to2010.nc",
    ),
)
```

**Comment by Peter9192** [comment]
Alternatively you could try running the singularity container from the command line like this:

```
singularity run /projects/0/wtrcycle/singularity-images/ewatercycle-pcrg-grpc4bmi_setters.sif
```

and report the error message you get.

**Comment by Peter9192** [comment]
@jeromaerts running with `BmiClientSingularity` you can try to add `delay=5` and possible wrap in a try-catch block like so:

```
try:
     BmiClientSingularity(image, work_dir='/gpfs/work1/0/wtrcycle/users/jaerts/pcrglobwb_rhinemeuse_30min/', delay=5)
except Exception as e:
    print(e)
```

to see the error you get.

**Comment by jeromaerts** [comment]
@Peter9192 
`!singularity run /projects/0/wtrcycle/singularity-images/ewatercycle-pcrg-grpc4bmi_setters.sif`

Results in the following error message:
`Traceback (most recent call last):
  File "/usr/local/bin/run-bmi-server", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/grpc4bmi/run_server.py", line 109, in main
    model = build(args.name, args.path)
  File "/usr/local/lib/python2.7/dist-packages/grpc4bmi/run_server.py", line 67, in build
    class_ = getattr(importlib.import_module(module_name), class_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/PCR-GLOBWB_model/model/bmiPcrglobwb.py", line 8, in <module>
    import pcraster as pcr
ImportError: No module named pcraster`

**Comment by Peter9192** [comment]
En je draait dit vanaf een Jupyter notebook (te zien aan het uitroepteken)?

**Comment by jeromaerts** [comment]
Ja klopt. Met de ewatercycle.yml zoals in de comparison repo en met het standaard bash script om een jupyter lab omgeving op een node te runnen.

**Comment by Peter9192** [comment]
Switching back to English (oops!). Can you try to run it from the a normal bash shell (may use the one available in Jupyter lab). You can try to use `singularity exec ...... bash` instead of `singularity run`. Then you'll enter the environment inside the container where you can look around. Can you find out what python environment is running there? Why is pcraster not installed?

**Comment by sverhoeven** [comment]
Could you also try on a snellius compute node:
```
singularity run --cleanenv /projects/0/wtrcycle/singularity-images/ewatercycle-pcrg-grpc4bmi_setters.sif
```
Maybe your environment vars are confusing the container.

**Comment by jeromaerts** [comment]
This is the Python version running in the container: 

(base) [jaerts@tcn442 jaerts]$ . ~/mambaforge/bin/activate comparison
(comparison) [jaerts@tcn442 jaerts]$ singularity exec /projects/0/wtrcycle/singularity-images/ewatercycle-pcrg-grpc4bmi_setters.sif bash
Singularity> python
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

The --cleanenv comand does not seem to solve the problem.

**Comment by Peter9192** [comment]
Okay so you could try something like `pip freeze | grep pcraster` to see if pcraster is indeed missing. Note that the python version in the container is not supposed to be the same as the one you've loaded on your compute node. It's defined here: 

https://github.com/eWaterCycle/PCR-GLOBWB_model/blob/bmi_fixes_setters/Dockerfile#L11

**Comment by jeromaerts** [comment]
Unfortunately this issue persists when using a clean ewatercycle install on Mistral.

The python version in the container: Python 2.7.12 

pip freeze output:
Singularity> pip freeze
backports.ssl-match-hostname==3.7.0.1
basic-modeling-interface==0.2
certifi==2020.6.20
cftime==1.0.1
chardet==3.0.4
Cython==0.28.5
docker==4.3.1
docopt==0.6.2
enum34==1.1.10
futures==3.3.0
GDAL==2.1.3
grpc4bmi==0.2.4
grpcio==1.33.1
grpcio-reflection==1.33.1
idna==2.10
ipaddress==1.0.23
netCDF4==1.4.1
numpy==1.11.0
protobuf==3.13.0
Pyste==0.9.10
requests==2.24.0
semver==2.13.0
six==1.15.0
UNKNOWN==0.0.0
urllib3==1.25.11
websocket-client==0.57.0

There seems to be no pcraster installation and there is a package called UNKNOWN...

**Comment by BSchilperoort** [comment]
Closing as it's a stale/old issue
