### ISSUE TITLE
Include all imported 3rd party packages in setup.py:install_requires

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#29]
It is best practice to include all 3rd party packages that are imported in ewatercycle/**.py  files to be included in the install_requires list in the setup.py

However dask, scipy packages are missing in setup.py. Can they be added?

**Comment by Peter9192** [comment]
I just stumbled upon that as well. Should they be in setup.py or in requirements.txt though?

**Comment by Peter9192** [comment]
or both? RTD uses the requirements.txt, that's why I would like them there as well

**Comment by Peter9192** [comment]
Ahh, I just saw #24
