### ISSUE TITLE
Mistral: Singularity error Fatal kernal too old

### ISSUE THREAD

**Issue by jeromaerts** [eWaterCycle/ewatercycle#291]
When running singularity on Mistral compute node the following error occurs:
FATAL: kernel too old

This is the case for all ewatercycle hosted singularity containers except for ewatercycle-pcrg-grpc4bmi_setters.sif

The Singularity version available on Mistral: singularity/3.6.1-gcc-9.1.0

**Comment by Peter9192** [comment]
For my understanding: you have freshly build the singularity images using these instructions? 
https://ewatercycle.readthedocs.io/en/latest/system_setup.html#id2

**Comment by jeromaerts** [comment]
(mistral was offline for a while...) Freshly building singularity images did not solve the problem.

**Comment by Peter9192** [comment]
See the section "kernel too old errors" somewhere midway on this page. It seems to explain what could be going wrong. https://www.glue.umd.edu/hpcc/help/software/singularity.html

[dockerfile for pcrglob](https://github.com/eWaterCycle/PCR-GLOBWB_model/blob/bmi_fixes_setters/Dockerfile) derives from [pcraster-container](https://github.com/eWaterCycle/pcraster-container/blob/master/Dockerfile) which derives from ubuntu:16.04. --> Is that similar to what's running on Mistral?

[wflow dockerfile](https://github.com/eWaterCycle/wflow/blob/docker-fixes-2020.1.3/Dockerfile) derives from [continuumio/anaconda3](https://github.com/ContinuumIO/docker-images/blob/master/anaconda3/debian/Dockerfile) which derives from [debian:bullseye-slim](https://github.com/debuerreotype/docker-debian-artifacts/blob/de5fb2efd50a009baa2aaccd2b7874ec728bd7a9/bullseye/slim/Dockerfile), etc. --> This seems very much up to date.

Don't have much time to investigate further now, but perhaps it helps you get an idea of where to start looking

**Comment by SarahAlidoost** [comment]
This is reported in Mistral documentation https://docs.dkrz.de/doc/mistral/singularity.html#fatal-kernel-too-old
