### ISSUE TITLE
Generic model support

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#292]
If I have a model with bmi and grpc4bmi in a container,
it would be nice if I could directly point to that container from ewatercycle,
without having to make a new version or so pointing to that container.

Example 1: I'm working on a new branch of pcrglobwb. It would be nice if I could specify container image path instead of version
Example 2: Once we'll have a GenericDistributed model class, there would be many "versions" corresponding to various models. It might be nicer to just point to an image directly (or provide an easy way to configure versions/names). 

@RolfHut feel free to add your thoughts here

**Comment by RolfHut** [comment]
Adding to this: If I'm working on a (new) model I would like to test it without having to upload my 'in between' work to dockerhub. Is there a way to build a docker image and singularity image without it being on the hub?

**Comment by BSchilperoort** [comment]
We now have the [leakybucket example implementation](https://github.com/eWaterCycle/ewatercycle-leakybucket). This is a most basic example of an ewatercycle model and has documentation on how to add a model.
