### ISSUE TITLE
num2date returns different objects depending on model/unit

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#295]
It looks like `num2date` in the forcing module returns a cftime.datetimegregorian for pcrglob, but a normal datetime for marrmot/lisflood.

**Comment by sverhoeven** [comment]
The abstract class uses `only_use_cftime_datetimes=False` in num2date calls at https://github.com/eWaterCycle/ewatercycle/blob/c794ef752215bc8a663d87aab2374f68e0559b3d/src/ewatercycle/models/abstract.py#L234 to get a datetime object. 

Seems we also need add  `only_use_cftime_datetimes=False` to  https://github.com/eWaterCycle/ewatercycle/blob/c794ef752215bc8a663d87aab2374f68e0559b3d/src/ewatercycle/models/pcrglobwb.py#L260

**Comment by BSchilperoort** [comment]
It seems like this is an old issue. `num2date` does not appear in the ewatercycle package, nor the ewatercycle-pcrglobwb package
