### ISSUE TITLE
Input argument "shape" doesn't do anything in ewatercycle.forcing.load_foreign()

### ISSUE THREAD

**Issue by pauwiersma** [eWaterCycle/ewatercycle#299]
I'm trying to use MeteoSwiss gridded climate data (RhiresD & TabsD) as an input to wflow. I manually organized the data into a single NetCDF file containing all precipitation and temperature for the whole time range, just like in [this](https://github.com/eWaterCycle/ewatercycle/blob/main/docs/examples/wflow.ipynb) example with `ewatercycle.forcing.load_foreign()`. 
I want to do a cutout, which the load_foreign function says it supports through the `shape` input argument ([here](https://github.com/eWaterCycle/ewatercycle/blob/460002a93e29e2841323b1cf95c852a8f8261567/src/ewatercycle/forcing/__init__.py#L51)), but then it just outputs the entire region instead of the cutout. When I put an invalid path it also doesn't send an error message. 
This is true also for the rhine_sbm example, so it's not a problem of my forcing file. 

So I was wondering whether this input argument is supposed to work and it doesn't for now, or whether it's not supposed to work and it should actually not be part of the function. 
In any case I'm open to suggestions if this is not the right way to use foreign forcing data in ewatercycle. 
Thanks in advance!

**Comment by Peter9192** [comment]
You're right that it's not doing anything. I think we put it there for consistency with the generate forcing method. In the future we might want to add functionality like "forcing_data.plot", and then it'd be nice that it already has a shape attribute. 

I suppose we could have a clearer documentation for the shape argument.

Also I agree that it might make sense to validate the path when given. Good suggestion!

**Comment by BSchilperoort** [comment]
I don't think this issue is really valid for ewatercycle 2.1 anymore. The default forcing implementations now copy the shape to the output directory (so it can be used for computing the basin area, and for plotting). `load_foreign` is also gone.
