### ISSUE TITLE
Sporadic FutureTimeoutErrors on model.setup

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#303]
Every now and again we encounter a grpc.FutureTimeoutError on calling model.setup. This happened at least for pcrglob, marrmotm01, and marrmotm14. There seem to be no clear circumstances that trigger the problem.

Especially for marrmot with the calibration we start many instances this is problematic, as it will break the calibration routine. The timeout is already set to 300 seconds, which should be plenty for marrmot. Perhaps increasing the delay (currently default =5) might help?

**Comment by sverhoeven** [comment]
I think this has to do with the container not starting up quick enough. Exposing the grpc4bmi delay argument and setting to a couple of seconds should give enough time for the container to start.

**Comment by sverhoeven** [comment]
The latest release (which includes PR #305) adds a delay argument which could be used to give the model more time to start.
