### ISSUE TITLE
Why it failed when I try to download eWaterCycle?

### ISSUE THREAD

**Issue by forestbat** [eWaterCycle/ewatercycle#307]
![图片](https://user-images.githubusercontent.com/23413915/169999960-43cde80d-ea92-40c2-a4a1-f7fe871de70a.png)
It says"The requested name is valid, but no data of the requested type was found."，so where is wrong？

**Comment by Peter9192** [comment]
Hello @forestbat,
Thanks you for reaching out. I tried to run the exact same command it works on my laptop. Are you using WSL? I've sometimes got similar issues when WSL didn't have internet access, you can verify this by typing `ping google.com`. It should return something like 

```
PING google.com (142.250.186.46) 56(84) bytes of data.
64 bytes from fra24s04-in-f14.1e100.net (142.250.186.46): icmp_seq=1 ttl=116 time=9.27 ms
64 bytes from fra24s04-in-f14.1e100.net (142.250.186.46): icmp_seq=2 ttl=116 time=10.6 ms
```

**Comment by forestbat** [comment]
> Hello @forestbat, Thanks you for reaching out. I tried to run the exact same command it works on my laptop. Are you using WSL? I've sometimes got similar issues when WSL didn't have internet access, you can verify this by typing `ping google.com`. It should return something like
> 
> ```
> PING google.com (142.250.186.46) 56(84) bytes of data.
> 64 bytes from fra24s04-in-f14.1e100.net (142.250.186.46): icmp_seq=1 ttl=116 time=9.27 ms
> 64 bytes from fra24s04-in-f14.1e100.net (142.250.186.46): icmp_seq=2 ttl=116 time=10.6 ms
> ```
No，I'm not using WSL，it's Windows 11，and I'm using clash to access google.com.
In fact I can ping to google in several ms，however I always can‘t get environment.yml from raw.githubusercontent.com.

**Comment by Peter9192** [comment]
Looking a bit further into the error message, it looks like this one: https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2#WSANO_DATA 

Not sure why this happens. The link (raw.gh...) is obtained by clicking the edit button for the file as it is listed on the repo, here:  https://github.com/eWaterCycle/ewatercycle/blob/main/environment.yml. Are you able to access that one?

**Comment by forestbat** [comment]
> Looking a bit further into the error message, it looks like this one: https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2#WSANO_DATA
> 
> Not sure why this happens. The link (raw.gh...) is obtained by clicking the edit button for the file as it is listed on the repo, here: https://github.com/eWaterCycle/ewatercycle/blob/main/environment.yml. Are you able to access that one?

Yes I can，thanks.
