### ISSUE TITLE
Crashed when execute “mamba create environment”

### ISSUE THREAD

**Issue by forestbat** [eWaterCycle/ewatercycle#310]
https://pastebin.ubuntu.com/p/dTBNRf7bnC/
You can see crash report in this，so how to solve this problem？

**Comment by Peter9192** [comment]
Looks like mamba or conda has problems. Perhaps try the standard/old `conda env create` instead of `mamba env ...`, or try up/downgrading your conda/mamba version?

**Comment by forestbat** [comment]
> Looks like mamba or conda has problems. Perhaps try the standard/old `conda env create` instead of `mamba env ...`, or try up/downgrading your conda/mamba version?

It still crashed，with a same crash report as https://pastebin.ubuntu.com/p/dTBNRf7bnC/.

**Comment by Peter9192** [comment]
Did you identify the problem?

**Comment by forestbat** [comment]
> Did you identify the problem?

No，however I think it shouldn't be placed here for a long time，if I need，I will reopen or reply you at least.

**Comment by Peter9192** [comment]
Okay, thanks for getting back to it.
