### ISSUE TITLE
Link to model home pages in model class doc strings

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#313]
The [ewatercycle documentation website](https://ewatercycle.readthedocs.io/en/latest/user_guide.html#Models) has links to the model home pages. However the model classes in the `ewatercycle.models` module only mentions the name. It would be nice if you could learn more about the model from just following the link in the API documentation.

**Comment by BSchilperoort** [comment]
Not applicable anymore, as the models have been moved to their own plugins.
