### ISSUE TITLE
esmvaltool update breaks Marrmot forcing

### ISSUE THREAD

**Issue by RolfHut** [eWaterCycle/ewatercycle#322]
I think an update in esmvaltool, or some other update somewhere, has broken the marrmot forcing routine in eWaterCycle.

line 73 in https://github.com/eWaterCycle/ewatercycle/blob/main/src/ewatercycle/forcing/_marrmot.py assumes that the first element in recipe_output contains the final resulting .mat file, but it does not anymore: now it points to the preproc directory. 

I think line 73 needs to point more explicitly to  the .mat file, without relying on the order of recipe_output to remain the constant?

See attached screenshot of the output:

![Screenshot 2022-11-01 at 10 52 11](https://user-images.githubusercontent.com/3808328/199207119-a43dfab3-dee5-4ab6-8e3c-d1752d8778fa.png)

**Comment by Peter9192** [comment]
This is where ewatercycle picks up the forcing file:

https://github.com/eWaterCycle/ewatercycle/blob/f384c186784e9745166452e9a6ccd47d48c5f136/src/ewatercycle/forcing/_marrmot.py#L71-L73

That index-based lookup seems a bit fragile indeed

**Comment by Peter9192** [comment]
Since https://github.com/ESMValGroup/ESMValCore/commit/49c65db048ee07da3aaa58628bff020cbe4d8113, preproc files are also included in the output retreived from the esmvaltool python api, unless the setting `remove_preproc_dir` is True.

**Comment by Peter9192** [comment]
It would be good to add a check that we indeed get a `.mat` file in `ewatercyce/forcing/_marrmot.py`
