### ISSUE TITLE
Replace config validation with pydantic validation

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#332]
In #324 I wanted to print a deprecation message when `container_engine: singularity` was used in the config file. So I wanted to add an extra validation rule. 

Current validation code is copied from matplotlib and is not easy to extend. It would be nice to use [pydantic](https://docs.pydantic.dev/).

Something like

```python
ContainerEngineEnum(str, Enum):
  docker= 'docker'
  apptainer = 'apptainer'
  singularity = 'singularity'

class Config(BaseModel):
  container_engine:ContainerEngineEnum = ContainerEngineEnum.docker
  parameterset_dir: DirectoryPath
  parameter_sets: dict[str,ParameterSet]
  ...

  @validator('container_engine')
  def singularity_deprecated(self, value):
    if value == ContainerEngineEnum.singularity:
       warnings.warn(
            "singularity is deprecated, use apptainer instead",
            DeprecationWarning
        )

raw_config = <dict loaded from yaml string>
config = Config(**raw_config)
```

**Comment by Peter9192** [comment]
I would like this very much. In the example, I think the Enum object is a bit overkill, why not just use `Literal['docker', 'apptainer', 'singularity']`?
