### ISSUE TITLE
GH will remove subversion support in 2024

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#333]
On January 8, 2024, GitHub will remove support for Subversion.
See https://github.blog/2023-01-20-sunsetting-subversion-support/

Subversion is used to download example parameter sets at https://github.com/eWaterCycle/ewatercycle/blob/main/src/ewatercycle/parameter_sets/_example.py#L52 and https://github.com/eWaterCycle/ewatercycle/blob/main/src/ewatercycle/parametersetdb/datafiles.py#L36

We need to find an alternative way to download a subdirectory of a GH repo.

**Comment by Peter9192** [comment]
Perhaps we could use https://pypi.org/project/pooch/ to retreive them. And store them as a zipfile rather than a dir. Or require that all example parameter sets are published e.g. on Zenodo.

**Comment by sverhoeven** [comment]
We tried ghclone and gitdir, but they are rate limited pretty quickly. So we need to either authenticate against github to get a highter limit or come up with an alternative like sparse checkout or download whole repo zip and extracting part of it.

**Comment by BSchilperoort** [comment]
We now download the GH repo with https://github.com/eWaterCycle/ewatercycle/blob/ad99ebfbe9b83917ad079e7ee9e28bd761c79576/src/ewatercycle/base/parameter_set.py#L19

This downloads the whole zip and extracts part of it out.

subversion has already been removed from the dependencies
