### ISSUE TITLE
Use plugins to add models (and forcing?) to eWaterCycle

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#336]
Currently, to add models to eWaterCycle, one needs to modify the source code of the eWaterCycle python package (see https://ewatercycle.readthedocs.io/en/latest/adding_models.html#add-the-model-to-the-ewatercycle-python-package). This is cumbersome and can be intimidating for new users. 

An alternative would be to enable adding models as plugins. Then, you can write a plugin in a completely separate repo, and install it alongside eWaterCycle like so:

```bash
pip install ewatercycle
pip install ewatercycle-plugin  # exposes class ToyModel via an entrypoint
```

And it will automatically be discovered by eWaterCycle like so:

```py
from ewatercycle.models import ToyModel
model = ToyModel(version='latest')
```

We could make one (or a few) example repo's of eWaterCycle plugins, or a template repo with instructions on how to finalize it. 

I started a branch here to see what this would entail: https://github.com/eWaterCycle/ewatercycle/pull/335. Use https://github.com/eWaterCycle/ewatercycle-plugin to test it.

**Comment by BSchilperoort** [comment]
We should add an extra pypi package `ewatercycle-collection` so you can install ewatercycle+all plugins like `ewatercycle-wflow`, `ewatercycle-leakybucket` with a single pip install.

**Comment by sverhoeven** [comment]
We are now using entry points in package metadata, there are 2 other methods suggested at https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/ . 

I think entrypoints offers most flexiblity, but is harder to implement. Would be nice to have a look at those other methods to see if they could be a fit for this repo.

**Comment by Peter9192** [comment]
> We are now using entry points in package metadata, there are 2 other methods suggested at https://packaging.python.org/en/latest/guides/creating-and-discovering-plugins/ .
> 
> I think entrypoints offers most flexiblity, but is harder to implement. Would be nice to have a look at those other methods to see if they could be a fit for this repo.

The options are:

1. Naming conventions. In this case, we rely on plugins adhering to a fixed naming convention, for example all plugins should be called `ewatercycle_<somename>`
2. Namespace packages. In this case, you can have a plugin named `anything` on PyPi, and as long as it follows the same structure as `ewatercycle`, for example it has a module `ewatercycle.forcing` then the content of that module is available under `ewatercycle.forcing` alongside the contents of the original `ewatercycle.forcing` module.
3. Entrypoints. In this case, plugins explicitly specify which functions/modules they export, targeting the entrypoint groups specified in eWaterCycle.

I think namespace packages (option 2) can be quite confusing and would rather not go that way. I can see some value in the ease of relying on naming conventions. I feel the explicit option with entrypoints is the most robust.

**Comment by sverhoeven** [comment]
Thanks for having a look, so we will stick with entry points. It is nice to have the choice documented.

**Comment by Peter9192** [comment]
See #338
