### ISSUE TITLE
Drop ESMValTool dependency?

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#337]
Currently, `ewatercycle` depends on `esmvaltool-python`. This is quite a heavy package as it installs all dependencies for all (python) recipes included with esmvaltool. Also, we need to make PRs to ESMValTool to update hydrology recipes. 

One possibility would be to move the hydrology recipes (and diagnostic scripts) to eWaterCycle (or its plugins, see #335), and only rely on ESMValCore to execute them. The downside of this would be that there is no longer a central place where people can find all the hydrology recipes. But to be FAIR, we believe there shouldn't be that many...

Another alternative could be to spin off ESMValTool-Hydrology into its own small package.

**Comment by Peter9192** [comment]
Install esmvalcore still cumbersome due to cartopy dependency (non installable through pip)

**Comment by BSchilperoort** [comment]
It seems that the only way ESMValCore uses cartopy is for reading shape files. See [here](https://github.com/ESMValGroup/ESMValCore/blob/7cf8adebc052655e7630b71506f7420b6906c8ba/esmvalcore/preprocessor/_mask.py#L11) and [here](https://github.com/ESMValGroup/ESMValCore/blob/7cf8adebc052655e7630b71506f7420b6906c8ba/esmvalcore/preprocessor/_mask.py#L254).

Ideally ESMValCore would use a lighter package that doesn't depend on gdal binaries for just reading a shapefile.

Although they also use Fiona, which depends on GDAL too.

**Comment by sverhoeven** [comment]
In #365 you can now build a ESMvalTool recipe optionally with your local diagnostic script. So you no longer need to modify the ESMValTool repo to add a recipe. 

The classic models (Marrmot, hype, etc.) still use diagnostic scripts that comes from the ESMValTool Python package so we still depend on that package. We could copy the diagnostic script to the eWaterCycle plugin, then we could have ESMValCore as dep and drop ESMValTool as dep.

**Comment by sverhoeven** [comment]
On further inspection at https://github.com/eWaterCycle/ewatercycle/blob/ad99ebfbe9b83917ad079e7ee9e28bd761c79576/src/ewatercycle/esmvaltool/diagnostic/copier.py#L6 and all other diagnostics in https://github.com/ESMValGroup/ESMValTool/tree/main/esmvaltool/diag_scripts/hydrology depend on `esmvaltool.diag_scripts.shared` module. 

I do not see a way to not depend on ESMValTool package.

So this issue can not be implemented.
