### ISSUE TITLE
Host Docker images on GH packages

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#343]
Docker will ask for money to have an org within Docker Hub in 2 months. 
We are part of the sponsored OSS on Docker Hub, but we will renew this every year.

We should switch to another registry like GH Packages.

I already tested it with https://github.com/eWaterCycle/hype-bmi/pkgs/container/hype-grpc4bmi and seems to work.

To switch we would have to
1. Publish all images from https://hub.docker.com/u/ewatercycle 
2. Change src/ewatercycle/models/* to use new image location

**Comment by Peter9192** [comment]
https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

> We’d also like to clarify that public images will only be removed from Docker Hub if their maintainer decides to delete them. We’re sorry that our initial communications failed to make this clear.

So it might be enough to use GHCR (or another alternative) only for new images.

**Comment by BSchilperoort** [comment]
We're using GHCR for new images, which are linked to the repositories hosting the plugins. There is no immediate need to move old images.

If Docker changes their mind we can reopen this issue.
