### ISSUE TITLE
Possible to instantiate abstractclass while it shouldn't?

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#37]
I think there might be a bug in the definition of the model API, as I seem to be able to instantiate classes for which not all methods are defined. Maybe I just don't understand it well enough though. 

Current implementation MWE:
```python
class AbstractModel:
    __metaclass__ = ABCMeta   # this is how it's currently implemented
    @abstractmethod
    def setup(self): pass

AbstractModel()   # works (while it shouldn't)
```

I think it can be fixed like this:
```python
class AbstractModel(metaclass=ABCMeta):
    @abstractmethod
    def setup(self): pass

AbstractModel()  # gives TypeError (as it should)
```

Was there a reason to do it like the first MWE?

**Comment by sverhoeven** [comment]
I somehow reverted back to Python 2 behavior, will create PR to fix.
