### ISSUE TITLE
Example plugin repo

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#370]
Use leaky bucket model
https://github.com/eWaterCycle/ewatercycle-plugin
Reuse/expand https://github.com/eWaterCycle/ewatercycle-plugin

See https://github.com/eWaterCycle/ewatercycle-leakybucket
 
TODO:

- [x] Upload to PyPI

**Comment by sverhoeven** [comment]
Edit with https://excalidraw.com/
![Untitled-2023-09-21-1447](https://github.com/eWaterCycle/ewatercycle/assets/1713488/3f1e22bf-005c-48eb-bbb0-7dde13335d3c)

**Comment by sverhoeven** [comment]
Pointing to https://github.com/eWaterCycle/ewatercycle-leakybucket in https://github.com/eWaterCycle/ewatercycle/pull/383
