### ISSUE TITLE
On release create DOI

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#38]
On https://zenodo.org/account/settings/github/ flip switch for this repo.

After release a DOI badge can be added to README.

**Comment by sverhoeven** [comment]
@nielsdrost do you want to use your account to tie the ewatercycle package to Zenodo or can I use mine?

**Comment by nielsdrost** [comment]
@sverhoeven feel free to use yours

**Comment by sverhoeven** [comment]
Thanks, I flipped the switch on Zenodo.

**Comment by Peter9192** [comment]
DOI is created (https://zenodo.org/record/5119390) and badge added to README
