### ISSUE TITLE
Make V2 Release

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#384]
- [x] Remove plugins from main repo
- [x] ~Drop dependency on ESMValTool (keep ESMValCore only, #337)~
- [x] Make v2-beta release of ewatercycle

Move plugins to their own repo

- [x] hype
- [x] lisflood
- [x] marrmot
- [x] pcrglobwb
- [x] wflow

For each model:

- Copy to own repo
- ~Diagnostics script from ESMValTool to plugin repo~
- Documentation --> example notebooks
- CI --> run tests with v2-beta (later v2)
- Publish on PyPI
- Zenodo
- RSD entries (list on project output page and/or related to ewatercycle software page, no separate software page for each plugin)
- Link to plugin from ewatercycle main docs ("Endorsed plugins")

Finally:

- [x] Update documentation user-guide to use plugins (and document their installation at the top of the notebook)
- [x] Make V2 release of ewatercycle
- [ ] Publish plugins on PyPI with correct ewatercycle version

**Comment by sverhoeven** [comment]
1. Make repo

At https://github.com/new?template_name=ewatercycle-leakybucket&template_owner=eWaterCycle

    * set owner to eWaterCycle
    * set name to ewatercycle-hype

1. Remove plugin guide + demo notebook

```bash
git rm plugin_guide.md
git rm demo_containerized_model.ipynb 
```

1. Search & replace (case sensitive)

    1. `Hype` -> `Hype` 
    2. `leakybucket` -> `hype`

1. Rename dir

```bash
git mv src/ewatercycle_leakybucket/ src/ewatercycle_hype
```

1. Update description in pyproject.toml

1. Copy files from core to plugin

```bash
cp ../ewatercycle/src/ewatercycle/plugins/hype/*py src/ewatercycle_hype/
cp -r ../ewatercycle/docs/plugins/hype docs
rm docs/index.rst
cp -r ../ewatercycle/tests/plugins/hype tests/
```

Commit with link to commit of version

```
https://github.com/eWaterCycle/ewatercycle/commit/ad99ebfbe9b83917ad079e7ee9e28bd761c79576
```

1. Update readme

1. Add forcing entry point to pyproject.toml

```toml
[project.entry-points."ewatercycle.forcings"]
HypeForcing = "ewatercycle_hype.forcing:HypeForcing"
```

1. Put back version

In `"src/ewatercycle_leakybucket/__init__.py"`

```python
__version__ = "0.1.0"
```

And remove version field from pyproject.toml

1. Depend on ewatercycle>=2.0.0

Edit pyproject.toml

1. Enable Zenodo integration

On https://zenodo.org/account/settings/github/
flip the switch for ewatercycle-hype

1. Update imports in python files

Rename `ewatercycle.plugins.hype` to `ewatercycle_hype`

1. Run tests locally

```bash
# mamba install
pip install ../ewatercycle
pip install -e .
pip install pytest
pytest
```

1. Add CI

1. RSD

Create entry

Invite maintainers Stefan,Bart,Peter

**Comment by sverhoeven** [comment]
https://github.com/eWaterCycle/ewatercycle-hype

* [x] Copy to own repo
* ~[x] Diagnostics script from ESMValTool to plugin repo~
* [x] Documentation --> example notebooks
* [x] CI --> run tests with v2-beta (later v2)
* [x] Publish on PyPI
* [x] Zenodo
* [x] RSD entries (list on project output page and/or related to ewatercycle software page, no separate software page for each plugin) 
* [x] Link to plugin from ewatercycle main docs ("Endorsed plugins")

**Comment by sverhoeven** [comment]
https://github.com/eWaterCycle/ewatercycle-lisflood

* [x] Copy to own repo
* ~[ ] Diagnostics script from ESMValTool to plugin repo~
* [x] Documentation --> example notebooks
* [x] CI --> run tests with v2-beta (later v2)
* [x] Publish on PyPI
* [x] Zenodo
* [x] RSD entries (list on project output page and/or related to ewatercycle software page, no separate software page for each plugin) 
* [x] Link to plugin from ewatercycle main docs ("Endorsed plugins")

**Comment by sverhoeven** [comment]
https://github.com/eWaterCycle/ewatercycle-marrmot

* [x] Copy to own repo
* ~[ ] Diagnostics script from ESMValTool to plugin repo~
* [x] Documentation --> example notebooks
* [x] CI --> run tests with v2-beta (later v2)
* [x] Publish on PyPI
* [x] Zenodo
* [x] RSD entries (list on project output page and/or related to ewatercycle software page, no separate software page for each plugin) 
* [x] Link to plugin from ewatercycle main docs ("Endorsed plugins")

**Comment by sverhoeven** [comment]
https://github.com/eWaterCycle/ewatercycle-pcrglobwb

* [x] Copy to own repo
* ~[ ] Diagnostics script from ESMValTool to plugin repo~
* [x] Documentation --> example notebooks
* [x] CI --> run tests with v2-beta (later v2)
* [x] Publish on PyPI
* [x] Zenodo
* [x] RSD entries (list on project output page and/or related to ewatercycle software page, no separate software page for each plugin) 
* [x] Link to plugin from ewatercycle main docs ("Endorsed plugins")

Had to rename existing private repo

**Comment by sverhoeven** [comment]
https://github.com/eWaterCycle/ewatercycle-wflow

* [x] Copy to own repo
* ~[ ] Diagnostics script from ESMValTool to plugin repo~
* [x] Documentation --> example notebooks
* [x] CI --> run tests with v2-beta (later v2)
* [x] Publish on PyPI
* [x] Zenodo
* [x] RSD entries (list on project output page and/or related to ewatercycle software page, no separate software page for each plugin) 
* [x] Link to plugin from ewatercycle main docs ("Endorsed plugins")

**Comment by BSchilperoort** [comment]
V2 was released successfully, including all model plugins.
