### ISSUE TITLE
CFG.load_from_file() does not change the list of available parameter sets, even when pointing to a correct ewatercycle.yaml file

### ISSUE THREAD

**Issue by RolfHut** [eWaterCycle/ewatercycle#386]
when load_from_file() in the CFG subpackage is called the parameters in the yaml file given as argument are not added to the list of available parameters as is specified in the documentation. 
<img width="773" alt="Screenshot 2023-10-05 at 22 43 46" src="https://github.com/eWaterCycle/ewatercycle/assets/3808328/500f6e36-1e8c-40bf-b468-4adcb6940872">

**Comment by RolfHut** [comment]
Correction! 
it does not throw an error when paths in the specified yaml file are incorrect, but rather just doesn't add that parameter set to the list!

**Comment by RolfHut** [comment]
(also: oranje river is just misleading, I vote either oranje rivier or orange river...)

**Comment by BSchilperoort** [comment]
With some local testing on my machine, it seems that this is an issue with the version on the SRC instance you were using (ewatercycle==1.4.1). On ewatercycle latest/2.0.0b2, the parameter sets with absolute paths seem to be loaded correctly.

eWaterCycle 2.0 should be out soon™, and then this issue should be resolved.

**Comment by RolfHut** [comment]
if that is the case, let's close this issue!
