### ISSUE TITLE
Broken plugin messes up watercycle.models

### ISSUE THREAD

**Issue by BSchilperoort** [eWaterCycle/ewatercycle#391]
If a plugin's model breaks upon import, this will mess with the ewatercycle.models entry point. This should be avoided somehow (e.g. a try/except)

**Comment by sverhoeven** [comment]
Isnt this what you want to happen. 

For example in `ewatercycle_wflow/model.py` I raised an exception in to the top of the file.

```python
In [1]: import ewatercycle.models
/home/stefanv/mambaforge/envs/ewatercycle/lib/python3.10/site-packages/esmvalcore/experimental/_warnings.py:13: UserWarning:
  Thank you for trying out the new ESMValCore API.
  Note that this API is experimental and may be subject to change.
  More info: https://github.com/ESMValGroup/ESMValCore/issues/498
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 import ewatercycle.models

File ~/mambaforge/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle/models.py:33
     31 # Expose as "from ewatercycle.models import Model" for backward compatibility
     32 for _model in _model_entrypoints:
---> 33     globals()[_model.name] = _model.load()

File ~/mambaforge/envs/ewatercycle/lib/python3.10/site-packages/importlib_metadata/__init__.py:210, in EntryPoint.load(self)
    205 """Load the entry point from its definition. If only a module
    206 is indicated by the value, return that module. Otherwise,
    207 return the named object.
    208 """
    209 match = self.pattern.match(self.value)
--> 210 module = import_module(match.group('module'))
    211 attrs = filter(None, (match.group('attr') or '').split('.'))
    212 return functools.reduce(getattr, attrs, module)

File ~/mambaforge/envs/ewatercycle/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File ~/mambaforge/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle_wflow/model.py:2
      1 """eWaterCycle wrapper around WFlow BMI."""
----> 2 raise Exception('Kaput')
      4 import datetime
      5 import logging

Exception: Kaput
```

Now its clear what is going wrong and that you need to look at the stack trace to find which plugin is kaput.

If we add a try/except around the load() call we have to give a warning that is easily ignored and later when you try to use a model it is somehow missing.

**Comment by Peter9192** [comment]
Raising rather than warning makes sense, but perhaps we could still catch the initial exception and re-raise it with a clearer message? E.g. "It looks like there's a problem with the following plugin: xxx. You can report the issue here. In the meantime, you can try uninstalling this plugin and/or ..."

**Comment by BSchilperoort** [comment]
> catch the initial exception and re-raise it with a clearer message

That's a good idea :+1: 

I shortly discussed this issue with Stefan yesterday, and the conclusion was that if we have an environment where _all_ packages are pinned (e.g. w/ conda-lock) we would avoid this problem as well. We can make sure that running ewatercycle.models is possible when generating the locked environment.
