### ISSUE TITLE
Add Zenodo doi parameter set downloader

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#4]
Some datasets are available on Zenodo. We should have a copier that can retrieve datafiles from a Zenodo doi.

**Comment by sverhoeven** [comment]
Refs #118 where https://github.com/eWaterCycle/ewatercycle/blob/376de2eb7afb0b64518319d310471293300ad2b8/ewatercycle/parameter_sets/__init__.py#L58 can be passed a DOI to download

**Comment by BSchilperoort** [comment]
This is implemented now.

https://github.com/eWaterCycle/ewatercycle/blob/ad99ebfbe9b83917ad079e7ee9e28bd761c79576/src/ewatercycle/base/parameter_set.py#L228-L238
