### ISSUE TITLE
Change default config directory to include UID

### ISSUE THREAD

**Issue by Daafip** [eWaterCycle/ewatercycle#409]
Currently the default directory created includes a specified prefix and timestap. 
https://github.com/eWaterCycle/ewatercycle/blob/b4ea453727aef571dbc18459d1804c8f86c75ff0/src/ewatercycle/base/model.py#L129

Works well when you do 'linear' modeling, but can cause some headache (_expecially if you dont realise as a novice user_) when you move to running many models at once or in parallel. 
I heard @RolfHut had a similar issue generating two sets of forcing in the same cell for example.

Of course you can specify a custom directory, which I did as a fix in the end for my use case. 
But I would argue adding a unique identifyer would smooth things out, something like: 
```py
f"{folder_prefix}_{timestamp}_{UID}"
```
Where the UID could be a random generated string for example (would resemble somewhat of a git commit to the user). 

What are your thoughts on this?

**Comment by BSchilperoort** [comment]
I would not be against this. A short uid would be nicer than a long one though (to avoid too much visual clutter).

**Comment by Peter9192** [comment]
This is exactly why the config dir can be specified in the call to `model.setup`, so what you call a "fix" is actually simply how we designed this. Would it have helped if we documented this option better?

I'm not against changing the default per sé, but I agree with Bart that it should still be legible and meaningful to the user, and I think the current default does a pretty good job at that.

**Comment by Peter9192** [comment]
By the way: what do you mean with UID? I think of user ID, but that doesn't seem to be what you are describing here.

**Comment by Daafip** [comment]
> is actually simply how we designed this

Fair point



> Would it have helped if we documented this option better?

Just looked throught the model documentation and it's clear enough i'd say.
