### ISSUE TITLE
Check contributor list

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#42]
The CITATION.cff and .zenodo.json list the contributors to the package. We should check that this list is complete.

**Comment by sverhoeven** [comment]
Also setup.py has author fields. See ESMValCore for example.

**Comment by Peter9192** [comment]
https://github.com/ESMValGroup/ESMValTool/blob/659217ae091b46520313d27af23cc1bc54142127/setup.py#L188

**Comment by Peter9192** [comment]
Addressed in #194.
