### ISSUE TITLE
In docs link to external types

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#43]
Use [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) to link to numpy, xarray, grpc4bmi types.

**Comment by Peter9192** [comment]
Yes, good idea. Example of how this is done in ESMValTool: 

https://github.com/ESMValGroup/ESMValTool/blob/b2e0cd8cafc805ec32fdd538a0a9d74714cabc6b/doc/sphinx/source/conf.py#L422-L437

**Comment by Peter9192** [comment]
Added in #143
