### ISSUE TITLE
Bump required Python + ruff + no more setup.py|setup.cfg

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#441]
We should do a pass to update everything except the code and test suite.

Must haves
- [x] Python 3.12
- [x] Ruff replaces flake8 + black + isort
  - [x] in lint ghaction run ruff and mypy
- [x] Delete setup.cfg + setup.py + (MANIFEST.in?)
- [x] Drop bump2version
  - use https://github.com/sphinx-toolbox/sphinx-pyproject to get version for docs/conf.py?
- [x] clean precommit, 
   -  drop bad mypy precommit hook
 - [x] drop .zenodo.json use RSD instead of https://zenodo.org/communities/nlesc/records
 - [x] use new pypi publish ghaction as it no longer needs a secret
 - [x] reproducable Lock file for dependencies

Nice to haves
- less config files
  - [x] Move docs/requirements.txt to docs optional dep in pyproject.toml
  - [x] does ruff to editorconfig stuff?
  - [x] .zendo.json is only used for community, replace with https://research-software-directory.org/organisations/netherlands-escience-center?tab=software&order=is_featured
- stop using sonar, 
  - [x]  use codecov for coverage, 
  - [x] ruff will be green or red, you will not have any warnings to show. So we dont have 2 different linters (precommit/flake/ruff and sonarcloud)
  - [x] replace sonarcloud badges with mypy/ruff/coverage badges
- [x] bump docs to latest/best versions
  - [x] update intersphinx urls
  - [x] remove unused napoleon_custom_sections ?
  - [ ] fix docstrings as ` pytest --doctest-modules src` is failing too much
- [x] .vscode settings that installs python, ruff extensions
- [x] .devcontainer that installs deps
- [ ] publish to test pypi on each push

**Comment by sverhoeven** [comment]
We could move .readthedocs.yaml to docs/ and set path at https://readthedocs.org/dashboard/ewatercycle/edit/

**Comment by BSchilperoort** [comment]
> Delete MANIFEST.in?

You can specify files to include/exclude in the packaging with hatch https://hatch.pypa.io/latest/config/build/#patterns

**Comment by BSchilperoort** [comment]
> use https://github.com/sphinx-toolbox/sphinx-pyproject to get version for docs/conf.py?

Adding this should solve that:
```py
from importlib.metadata import version as get_version

# The short X.Y version.
version = get_version("ewatercycle").split("+")[0]
# The full version, including alpha/beta/rc tags.
release = get_version("ewatercycle")
```

And in `__init__.py`
```py
importlib.metadata import version
__version__ = version(__package__) 
```


It would be possible to only have a version specified in `pyproject.toml` this way.

**Comment by sverhoeven** [comment]
Lock file could be autogenerated in GH workflow for example https://github.com/conda/conda-lock/blob/main/.github/workflows/update-lockfile.yaml

**Comment by sverhoeven** [comment]
See https://github.com/eWaterCycle/ewatercycle-leakybucket/blob/main/.github/workflows/publish.yml how to do publish without secret token

**Comment by sverhoeven** [comment]
The conda-lock.yml is using Python 3.12.4 . The lock is also used in ci for pytest and mypy in #449 .
