### ISSUE TITLE
Tests included in distro

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#47]
When I do `python setup.py sdist bdist_wheel` then archives in `dist/` contain the `ewatercycle/` packages, but also the files in  `tests/`. The installed package should not include the tests.

This is caused by https://github.com/eWaterCycle/ewatercycle/blob/c7f137b6d699cb71aa7a432bcc8fd78930ed4b94/setup.py#L32

The tests can be excluded with
```python
 packages=find_packages(exclude=['tests', 'tests.*']),
```

**Comment by Peter9192** [comment]
Adressed in #191
