### ISSUE TITLE
Sonarcloud spam

### ISSUE THREAD

**Issue by stefsmeets** [eWaterCycle/ewatercycle#51]
This sonarcloud spam is driving me crazy, and not helpful if there are no problems. A recent example:

![image](https://user-images.githubusercontent.com/873520/114678806-e52c0300-9d0b-11eb-8123-7bd6c990153d.png)

Would it be possible to turn those off? We already get the checks at the bottom of the PR.
https://community.sonarsource.com/t/disable-github-merge-request-comments/18520/23 

_Project page > Administration > General Settings > Pull Request and uncheck the option Enable summary comment._

**Comment by Peter9192** [comment]
It typically happens when you push many commits shortly after another. They disappear again after some time. We agree that this is something we can live with.
