### ISSUE TITLE
`model.setup` return type for `cfg_file` should match `model.initialize` input type

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#52]
According to pymt, you should be able to do

```Python
cfg_file, cfg_dir = model.setup(...)
model.initialize(cfg_file)
```

This currently doesn't work as `setup` return a Path, whereas `initialize` expects a str. I think we should make `setup` return a str.

**Comment by SarahAlidoost** [comment]
steup should get `cfg_dir` as a string too.
