### ISSUE TITLE
Add `get_value_at_indices` to public interface of ewatercycle model classes.

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#53]
and `set_value_at_indices` as well.

**Comment by sverhoeven** [comment]
This will become blocking when we start writing notebooks that only need subset of values or need to alter part of the model state.

**Comment by sverhoeven** [comment]
The PyMT does not seem call `get_value_at_indices` or `get_value_at_indices` anywhere. 

However get_value() has `at` argument which I thought would use get_value_at_indices, but it does not.
See https://github.com/csdms/pymt/blob/79855ce2393c382d3f7b0e22b0d5a55fd582fe21/pymt/framework/bmi_bridge.py#L356-L357 .

So I will just add get_value_at_indices and set_value_at_indices to AbstractModel.

**Comment by Peter9192** [comment]
For the use case you describe, as a workaround, you can always do `get_value`, overwrite part of the returned array, and then call `set_value` with the full array. But I agree it would be nicer to select a subset.

I would argue that it's even more useful to be able to `get_value_at_coords` or something like that. Ideally the user should not have to worry about the internal indices used in the model.

**Comment by sverhoeven** [comment]
PR #108 will add get_value_at_coords
