### ISSUE TITLE
Conflict about the naming of work_dir and cfg_dir

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#61]
There is a conflict about the naming of `work_dir` (which is what grpc4bmi uses) and `cfg_dir` (which is what [PyMT uses](https://pymt.readthedocs.io/en/latest/usage.html)). In PyMT usage, the variable is named as `cfg_dir`. However, it is referred to `run` directory in the text. (cc @Peter9192)

**Comment by sverhoeven** [comment]
Agree each model should have `model.setup(cfg_dir=something)`

**Comment by Peter9192** [comment]
For the tech paper milestone let's make sure all public functions use `cfg_dir`. Renaming `work_dir` internally is not needed per se but would be nice for clarity and consistency. `grpc4bmi` uses `work_dir`, this should stay the same.

**Comment by sverhoeven** [comment]
Pcrglobwb, wlfow do not have cfg_dir or work_dir as argument for setup().  Will fix in #133
