### ISSUE TITLE
Marrmot forcing.generate: .data_files returns an empty tuple.

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#64]
I want to use `.load_xarray()` on marrmot forcing. When I run: 
```python
marrmot_output = forcing.generate(
    model='marrmot', 
    dataset='ERA5', 
    startyear=1990, 
    endyear=1990, 
    shapefile='Meuse/Meuse.shp',
)
```

I can get the output list:
```python
list(marrmot_output.recipe_output.values())[0]

diagnostic_daily/script:
  OutputFile('marrmot_ERA5_Meuse_1990_1990.mat')
```

Then, `.data_files` returns an empty tuple:
```python
list(marrmot_output.recipe_output.values())[0].data_files
()
```

**Comment by SarahAlidoost** [comment]
@stefsmeets Could you please help me with this issue?

**Comment by stefsmeets** [comment]
It seems like the marrmot preprocessor returns a `.mat` file, which is not a netcdf or image file, so it falls back to the generic type `OutputFile`. In the current implementation only netcdf files (which are returned as `DataFile` objects) can be loaded with `xarray`.

**Comment by stefsmeets** [comment]
`list(marrmot_output.recipe_output.values())[0].files` will give you a list of all the files from this task.

**Comment by sverhoeven** [comment]
Fixed in master branch, see https://github.com/eWaterCycle/ewatercycle/blob/c5cb64dfe252c63fa2c8e3ad86cc963cfe4f4abe/ewatercycle/models/marrmot.py#L121 

Can this issue be closed?

**Comment by stefsmeets** [comment]
`self.forcing_file = list(forcing.recipe_output.values())[0].files[0].filename `

This seems very fragile, 6 levels deep 😬

**Comment by sverhoeven** [comment]
Yeah, having `forcing.filenames[0]` would be much nicer.
