### ISSUE TITLE
Move creating work dir function out of model modules

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#67]
Now each model has a way to create a work dir when none is given. It would be nice if they could use the same method from some utils module.

The function should use a random string so running same model in parallel will create unique work dirs.

Also see https://github.com/eWaterCycle/ewatercycle/pull/56#pullrequestreview-640087896

**Comment by Peter9192** [comment]
Is it very bad practice to implement this as a method on the base class?

**Comment by sverhoeven** [comment]
It does not use any of the object properties so it could be a `@classmethod`, but having the method outside the class makes it easier to use elsewhere.

**Comment by BSchilperoort** [comment]
Was implemented in V2! :rocket: 

No random string is added, but the UTC timestamp is. Users can also specify their own cfg_dir.
