### ISSUE TITLE
forcing: long esmvaltool log info in notebooks

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#68]
Is there a way to summarize the main-log information or to use a scroll box in notebooks?

**Comment by Peter9192** [comment]
In jupyter lab you can collapse the output cell by clicking on the blue-ish vertical bar to the left of the cell. Is that enough or do you need something more sophisticated?

**Comment by sverhoeven** [comment]
Use [%%capture](https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-capture) notebook magic to capture output and later present in a terse way

**Comment by SarahAlidoost** [comment]
`%%capture` is not working with esmvalcore logger. Adding these lines at top of the notebooks will truncate the output: 

```python
import logging
logger = logging.getLogger('esmvalcore')
logger.setLevel(logging.WARNING)
```

See the output in this [docs](https://ewatercycle--163.org.readthedocs.build/en/163/examples/generate_forcing.html).
