### ISSUE TITLE
Intake overlap

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#7]
The parametersetdb package tries to do similar things as the [intake](https://intake.readthedocs.io/en/latest/) Python library.

We should look how this library and intake can co-exist. For example use intake catalogs for the `save_datafiles()` part.

The parameter sets for Hydrology models are now expected to be a tarball/directory + config file, while intake expects a catalog of data sets (files).

**Comment by sverhoeven** [comment]
ewatercycle package now does lot more. So overlap is not that prominent anymore, only [parameter set downloader](https://github.com/eWaterCycle/ewatercycle/blob/376de2eb7afb0b64518319d310471293300ad2b8/ewatercycle/parameter_sets/__init__.py#L75-L81) and it needs to save files to disk while intake gives you Python data objects which you can persist.

**Comment by Peter9192** [comment]
So shall we close the issue? We can always reopen, or open a new one, when we see a clear use case for intake, but right now it seems not immediately relevant.
