### ISSUE TITLE
Bug: forcing.generate wflow missing basin name 

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#72]
esmvaltool [recipe_wflow.yml](https://github.com/ESMValGroup/ESMValTool/blob/master/esmvaltool/recipes/hydrology/recipe_wflow.yml) contains the key `basin` that is used in the output filename. But, `forcing.generate` is missing the key. As an example, in the current implementation, the output name is `wflow_ERA5_wflow_dem_1990_1990.nc` which is not correct: '**wflow_dem'** should be replaced by the basin name.

**Comment by sverhoeven** [comment]
Basin is set at https://github.com/eWaterCycle/ewatercycle/blob/dfca1cbed2b741ef2e720e589c6efb21137b8d86/ewatercycle/forcing/_wflow.py#L64-L66
Does that fix it?
