### ISSUE TITLE
Allow datetime.date object as argument for get_grdc_data

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#73]
At the moment the start and end date must be given as 'YYYY-MM-dd' strings. To be more 

See https://github.com/eWaterCycle/ewatercycle/blob/c5cb64dfe252c63fa2c8e3ad86cc963cfe4f4abe/ewatercycle/observation/grdc.py#L23-L26

**Comment by SarahAlidoost** [comment]
@sverhoeven Considering issue #90 and pull request #109, can we close this issue?

**Comment by sverhoeven** [comment]
Yep, we decided to use ISO8601 formatted string with UTC timezone everywhere
