### ISSUE TITLE
Return datetime type for model.time

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#74]
At the moment when I want a [datetime object](https://docs.python.org/3/library/datetime.html#datetime-objects) from a model I have to do

```python
from datetime import datetime
from cftime import num2date
current_time: datetime = num2date(
    model.time,
    model.get_time_units(),
    only_use_cftime_datetimes=False
)
```

It would be nice if ewatercycle package would do the num2date call for me. 

For example by adding a property `time_as_datetime`:

```
from datetime import datetime
current_time: datetime = model.time_as_datetime
```

**Comment by sverhoeven** [comment]
need to add following methods to AbstractModel:
* model.time -> model.time_as_datetime
* model.end_time -> model.end_time_as_datetime
* model.start_time -> model.start_time_as_datetime

The `*as_datatime` functions should return same format as `ewatercycle.util.get_time('2021-06-30T00:00:00Z')` so UTC and hours/minutes/seconds==0.

The update loop for a gridded model will look like:
```python 
output = {}
output['time'] = []
start_time = get_time('2021-06-30T00:00:00Z')
while (model.time_as_datetime < model.end_time_as_datetime):
    model.update()
    current_time =model.time_as_datetime
    # Store model time and variable output after the spin up period
    if current_time  >= start_time:
        output['time'].append(current_time)
        value = model.get_value_at_coords('flux_out_Q', lon=[station_lat], lat=[station_lon])
        output['flux_out_Q'].append(value[0])
```

**Comment by sverhoeven** [comment]
Another option would be to add helper methods that return a iso8601 date string (`'2021-06-30T00:00:00Z'`) as we ask users to supply such strings in forcing/grdc/model.setup and we return it in model.pararmeters.

* model.time_as_isostr
* model.end_time_as_isostr
* model.start_time_as_isostr

**Comment by sverhoeven** [comment]
See overview of different usages of dates see #90

**Comment by sverhoeven** [comment]
We decided to go with the `*as_isostr` option.

The docs/examples/* notebooks should also be update to use `model.time_as_isostr`

**Comment by Peter9192** [comment]
Can't we have multiple options? 

So you could do 

```pyton
df = pd.DataFrame(...)
while model.time < model.end_time:
    datetime = model.datetime
    value = model.get_value_at_coords(...)
    df[datetime] = value
    print(f"processed time {model.isotime}")
```

**Comment by sverhoeven** [comment]
Ok lets add `model.*time_as_isostr` and `model.*time_as_datetime`.
