### ISSUE TITLE
Expose grdc station info method

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#9]
At the moment to get the location of a station you need fetch observations and look in the metadata of the xarray dataset.

```python
from ewatercycle.observation.grdc import get_grdc_data
ds = get_grdc_data('4147380', '1990-01-01, '1990-12-31')
lon = ds.grdc_longitude_in_arc_degree
lat = ds.grdc_latitude_in_arc_degree
```

The current grdc method requires giving a start and end date, but these are not required to get the metadata from the txt file. If dates are chosen wrong it could even result in an error.

It would be nice to have a method that can show the station info either from the station txt file or the [GRDC station catalogue](https://www.bafg.de/GRDC/EN/02_srvcs/21_tmsrs/211_ctlgs/catalogues_node.html). 

It would like to do 
```python
from ewatercycle.observation.grdc import get_grdc_station_info
station = get_grdc_station_info('4147380')
lon = station['grdc_longitude_in_arc_degree']
lat = station['grdc_latitude_in_arc_degree']
```

**Comment by sverhoeven** [comment]
get_grdc_data now returns tuple with metadata, see #109

**Comment by Peter9192** [comment]
> get_grdc_data now returns tuple with metadata, see #109

I think that sufficiently addresses the issue. If not, please reopen.
