### ISSUE TITLE
Lisflood model class still uses old `forcing_data`

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#92]
This breaks the package as soon as you do `from ewatercycle.models import something`.

**Comment by Peter9192** [comment]
And same for marrmot

**Comment by SarahAlidoost** [comment]
> This breaks the package as soon as you do `from ewatercycle.models import something`.

as lisflood is now in a PR #84, I will fix this there, because I had to merge master to re-solve conflict. And now tests are broken.

**Comment by SarahAlidoost** [comment]
> And same for marrmot

It will be fixed by #95.
