### ISSUE TITLE
Consistent handling of paths

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#93]
The ewatercycle user interface uses string formats to get path inputs. It would be helpful if we internally default to using standard `Path` representations as well. #82 implements a pathparser that converts input strings to pathlib objects. It would be nice use this throughout the package. 

It might also be nice to add some custom `__str__` methods so that the user never gets to see the internal representation.

**Comment by sverhoeven** [comment]
By fixing #113 we no longer leak paths to user with the public API.

Converting strings to Path objects is now duplicated in each model. We can make generic function in ewatercycle.util to perform this conversion so expanduser() and resolve() are called always. Something like

```python
def make_absolute(p: str) -> Path:
  return Path(p).expanduser().resolve()
```

**Comment by Peter9192** [comment]
Yep, like that 👍 

Don't we still leak paths when the user tries to inspect the ParameterSet or Forcing objects?

**Comment by Peter9192** [comment]
I made a start with something like that in https://github.com/eWaterCycle/ewatercycle/pull/107

**Comment by Peter9192** [comment]
`ewatercycle.parameter_sets.default.make_absolute()` can be reused in `ewatercycle.forcing.default`. Maybe move to `util`.
